---
apiVersion: v1
kind: Service
metadata:
  name: whoami
  labels:
    app: whoami
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5000
    externalIPs: 
    - 192.168.99.100
  selector:
    app: whoami
---  
apiVersion: apps/v1
kind: Deployment
metadata:
  name: whoami
spec:
  replicas: 5
  template:
    metadata:
      labels:
        app: whoami
    spec:
      containers:
      - name: whoami
        image: democontenidors/whoami:1.0
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        ports:
          - containerPort: 5000
